sudo: false
language: python

addons:
  apt_packages:
    - pandoc

matrix:
    include:
        - python: 2.7
          env: TOXENV=packaging
        - python: 3.5
          env: TOXENV=py3-pep8
        - python: 2.7
          env: TOXENV=py2-pep8

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install pypandoc
  - pip install tox

script:
  - tox

notifications:
  email: false

